// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package model

import (
	"context"
)

const taskCountByWorktree = `-- name: TaskCountByWorktree :one
SELECT COUNT(1) AS count
FROM tasks
WHERE worktree_id = ?1
  AND deleted_at IS NULL
`

func (q *Queries) TaskCountByWorktree(ctx context.Context, worktreeID *string) (int64, error) {
	row := q.queryRow(ctx, q.taskCountByWorktreeStmt, taskCountByWorktree, worktreeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
