/* tslint:disable */
/* eslint-disable */
/**
 * Go Template API - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface CreateNotePadBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 内容
   */
  content: string;
  /**
   * 标签页名称
   */
  name: string;
  /**
   * 项目ID（为空表示全局笔记）
   */
  projectId?: string;
}
export interface CreateProjectInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 项目描述
   */
  description: string;
  /**
   * �Ƿ�����·��
   */
  hidePath?: boolean;
  /**
   * 项目名称
   */
  name: string;
  /**
   * 本地项目目录路径（可非 Git 仓库）
   */
  path: string;
  /**
   * Worktree 基础路径（可选，默认为项目目录下的 worktrees 子目录）
   */
  worktreeBasePath?: string;
}
export interface PtyTestCreateInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 终端列数
   */
  cols: number;
  /**
   * xpty 输出编码，默认 utf-8
   */
  encoding: string;
  /**
   * 终端行数
   */
  rows: number;
  /**
   * 自定义 shell 命令，留空使用默认配置
   */
  shell: string;
  /**
   * 工作目录，可选
   */
  workingDir: string;
}
export interface OpenPathInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 目标路径
   */
  path: string;
}
export interface UploadClipboardImageInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 图片数据（base64 编码）
   */
  data: string;
  /**
   * 文件名
   */
  fileName: string;
}
export interface MessageResponseBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 提示信息
   */
  message: string;
}
export interface Project {
  createdAt: string;
  defaultBranch: string | null;
  deletedAt: string | null;
  description: string | null;
  hidePath: boolean;
  id: string;
  lastSyncAt: string | null;
  name: string;
  path: string;
  remoteUrl: string | null;
  updatedAt: string;
  worktreeBasePath: string | null;
}
export interface ItemsResponseProjectBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应列表
   */
  items: Project[] | null;
}
export interface MoveNotePadBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 排序索引
   */
  orderIndex: number;
}
export interface UpdateNotePadBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 内容
   */
  content?: string;
  /**
   * 标签页名称
   */
  name?: string;
}
export interface UpdateProjectInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * ��Ŀ����
   */
  description: string;
  /**
   * �Ƿ�����·��
   */
  hidePath: boolean;
  /**
   * ��Ŀ����
   */
  name: string;
}
export interface CreateBranchBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 基础分支
   */
  base: string;
  /**
   * 同时创建 Worktree
   */
  createWorktree: boolean;
  /**
   * 分支名称
   */
  name: string;
}
export interface CreateTaskBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 任务描述
   */
  description: string;
  /**
   * 截止日期
   */
  dueDate: string | null;
  /**
   * 优先级
   */
  priority: number;
  /**
   * 任务状态
   */
  status: 'todo' | 'in_progress' | 'done' | 'archived';
  /**
   * 标签
   */
  tags: string[] | null;
  /**
   * 任务标题
   */
  title: string;
  /**
   * 关联的 Worktree
   */
  worktreeId: string | null;
}
export interface TerminalRenameInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 新的终端标签名
   */
  title: string;
}
export interface Worktree_create_request {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 基础分支
   */
  baseBranch: string;
  /**
   * 分支名称
   */
  branchName: string;
  /**
   * 是否创建新分支
   */
  createBranch: boolean;
}
export interface TerminalCreateInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 终端列数
   */
  cols: number;
  /**
   * 终端行数
   */
  rows: number;
  /**
   * 终端标题
   */
  title: string;
  /**
   * 工作目录
   */
  workingDir: string;
}
export interface BindWorktreeBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * Worktree ID（null 表示解绑）
   */
  worktreeId?: string;
}
export interface CreateCommentBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 评论内容
   */
  content: string;
}
export interface MoveTaskBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 排序索引
   */
  orderIndex?: number;
  /**
   * 新状态
   */
  status?: string;
  /**
   * 关联 Worktree
   */
  worktreeId?: string;
}
export interface UpdateTaskBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 任务描述
   */
  description?: string;
  /**
   * 截止日期
   */
  dueDate?: string;
  /**
   * 优先级
   */
  priority?: number;
  /**
   * 标签
   */
  tags?: string[];
  /**
   * 任务标题
   */
  title?: string;
}
export interface Worktree_commit_request {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 提交信息
   */
  message: string;
}
export interface MergeBranchBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * Squash 合并后立即提交
   */
  commit: boolean;
  /**
   * 提交信息（仅 squash 合并生效）
   */
  commitMessage: string;
  /**
   * 源分支
   */
  sourceBranch: string;
  /**
   * 合并策略
   */
  strategy: 'merge' | 'rebase' | 'squash';
  /**
   * 目标分支
   */
  targetBranch: string;
}
export interface DeletedAt {
  Time: string;
  Valid: boolean;
}
export interface NotePadTable {
  content: string;
  createdAt: string;
  deletedAt: DeletedAt;
  id: string;
  name: string;
  orderIndex: number;
  projectId: string | null;
  updatedAt: string;
}
export interface ItemsResponseNotePadTableBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应列表
   */
  items: NotePadTable[] | null;
}
export interface ItemResponseNotePadTableBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: NotePadTable;
}
export interface ItemResponseProjectBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: Project;
}
export interface BranchInfo {
  hasWorktree: boolean;
  headCommit: string;
  isCurrent: boolean;
  isRemote: boolean;
  name: string;
}
export interface BranchListResult {
  local: BranchInfo[] | null;
  remote: BranchInfo[] | null;
}
export interface ItemResponseBranchListResultBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: BranchListResult;
}
export interface RefreshAllResult {
  /**
   * 刷新失败数量
   */
  failed: number;
  /**
   * 刷新成功数量
   */
  updated: number;
}
export interface ItemResponseRefreshAllResultBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: RefreshAllResult;
}
export interface TerminalSessionView {
  cols: number;
  createdAt: string;
  encoding: string;
  id: string;
  lastActive: string;
  projectId: string;
  rows: number;
  status: string;
  title: string;
  workingDir: string;
  worktreeId: string;
  wsPath: string;
  wsUrl: string;
}
export interface ItemsResponseTerminalSessionViewBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应列表
   */
  items: TerminalSessionView[] | null;
}
export interface Worktree {
  branchName: string;
  createdAt: string;
  deletedAt: string | null;
  headCommit: string | null;
  headCommitDate: string | null;
  id: string;
  isBare: boolean;
  isMain: boolean;
  path: string;
  projectId: string;
  statusAhead: number | null;
  statusBehind: number | null;
  statusConflicts: number | null;
  statusModified: number | null;
  statusStaged: number | null;
  statusUntracked: number | null;
  statusUpdatedAt: string | null;
  updatedAt: string;
}
export interface ItemsResponseWorktreeBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应列表
   */
  items: Worktree[] | null;
}
export interface PtyTestSessionView {
  cols: number;
  createdAt: string;
  encoding: string;
  id: string;
  rows: number;
  shell: string[] | null;
  workingDir: string;
  wsPath: string;
  wsUrl: string;
}
export interface ItemResponsePtyTestSessionViewBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: PtyTestSessionView;
}
export interface ProjectTable {
  createdAt: string;
  defaultBranch: string;
  deletedAt: DeletedAt;
  description: string;
  hidePath: boolean;
  id: string;
  lastSyncAt: string | null;
  name: string;
  path: string;
  remoteUrl: string;
  updatedAt: string;
  worktreeBasePath: string;
}
export interface WorktreeTable {
  branchName: string;
  createdAt: string;
  deletedAt: DeletedAt;
  headCommit: string;
  headCommitDate: string | null;
  id: string;
  isBare: boolean;
  isMain: boolean;
  path: string;
  project?: ProjectTable;
  projectId: string;
  statusAhead: number;
  statusBehind: number;
  statusConflicts: number;
  statusModified: number;
  statusStaged: number;
  statusUntracked: number;
  statusUpdatedAt: string | null;
  updatedAt: string;
}
export interface TaskTable {
  completedAt: string | null;
  createdAt: string;
  deletedAt: DeletedAt;
  description: string;
  dueDate: string | null;
  id: string;
  orderIndex: number;
  priority: number;
  project?: ProjectTable;
  projectId: string;
  status: string;
  tags: string[] | null;
  title: string;
  updatedAt: string;
  worktree?: WorktreeTable;
  worktreeId: string | null;
}
export interface ItemResponseTaskTableBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: TaskTable;
}
export interface TaskCommentTable {
  content: string;
  createdAt: string;
  deletedAt: DeletedAt;
  id: string;
  task?: TaskTable;
  taskId: string;
  updatedAt: string;
}
export interface ItemsResponseTaskCommentTableBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应列表
   */
  items: TaskCommentTable[] | null;
}
export interface UploadImageResponse {
  /**
   * 文件名
   */
  fileName: string;
  /**
   * 文件路径
   */
  path: string;
  /**
   * 文件大小（字节）
   */
  size: number;
}
export interface ItemResponseUploadImageResponseBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: UploadImageResponse;
}
export interface ItemResponseWorktreeBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: Worktree;
}
export interface PaginatedResponseTaskTableBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 本次返回数量
   */
  itemCount: number;
  /**
   * 响应列表
   */
  items: TaskTable[] | null;
  /**
   * 当前页码
   */
  page: number;
  /**
   * 每页数量
   */
  pageSize: number;
  /**
   * 记录总数
   */
  total: number;
}
export interface ItemResponseTerminalSessionViewBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: TerminalSessionView;
}
export interface ItemResponseTaskCommentTableBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: TaskCommentTable;
}
export interface MergeResult {
  conflicts: string[] | null;
  message: string;
  success: boolean;
}
export interface ItemResponseMergeResultBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: MergeResult;
}
declare global {
  interface Apis {
    health: {
      /**
       * ---
       *
       * [GET] 健康探测
       *
       * **path:** /api/v1/health
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      check<Config extends Alova2MethodConfig<MessageResponseBody>>(
        config?: Config
      ): Alova2Method<MessageResponseBody, 'health.check', Config>;
    };
    notepad: {
      /**
       * ---
       *
       * [GET] 获取记事板标签
       *
       * **path:** /api/v1/notepads
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 项目ID（为空表示全局笔记）
       *   projectId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应列表
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   items: Array<{
       *     content: string
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     id: string
       *     name: string
       *     orderIndex: number
       *     projectId: string | null
       *     updatedAt: string
       *   }> | null
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<ItemsResponseNotePadTableBody> & {
          params: {
            /**
             * 项目ID（为空表示全局笔记）
             */
            projectId?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ItemsResponseNotePadTableBody, 'notepad.list', Config>;
      /**
       * ---
       *
       * [POST] 创建记事板标签
       *
       * **path:** /api/v1/notepads/create
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 内容
       *   content: string
       *   // 标签页名称
       *   name: string
       *   // 项目ID（为空表示全局笔记）
       *   projectId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     content: string
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     id: string
       *     name: string
       *     orderIndex: number
       *     projectId: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<ItemResponseNotePadTableBody> & {
          data: CreateNotePadBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseNotePadTableBody, 'notepad.create', Config>;
      /**
       * ---
       *
       * [GET] 获取记事板标签详情
       *
       * **path:** /api/v1/notepads/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     content: string
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     id: string
       *     name: string
       *     orderIndex: number
       *     projectId: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      get<
        Config extends Alova2MethodConfig<ItemResponseNotePadTableBody> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseNotePadTableBody, 'notepad.get', Config>;
      /**
       * ---
       *
       * [POST] 删除记事板标签
       *
       * **path:** /api/v1/notepads/{id}/delete
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'notepad.delete', Config>;
      /**
       * ---
       *
       * [POST] 移动记事板标签顺序
       *
       * **path:** /api/v1/notepads/{id}/move
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 排序索引
       *   orderIndex: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     content: string
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     id: string
       *     name: string
       *     orderIndex: number
       *     projectId: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      move<
        Config extends Alova2MethodConfig<ItemResponseNotePadTableBody> & {
          pathParams: {
            id: string;
          };
          data: MoveNotePadBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseNotePadTableBody, 'notepad.move', Config>;
      /**
       * ---
       *
       * [POST] 更新记事板标签
       *
       * **path:** /api/v1/notepads/{id}/update
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 内容
       *   content?: string
       *   // 标签页名称
       *   name?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     content: string
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     id: string
       *     name: string
       *     orderIndex: number
       *     projectId: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      update<
        Config extends Alova2MethodConfig<ItemResponseNotePadTableBody> & {
          pathParams: {
            id: string;
          };
          data: UpdateNotePadBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseNotePadTableBody, 'notepad.update', Config>;
    };
    project: {
      /**
       * ---
       *
       * [GET] 项目列表
       *
       * **path:** /api/v1/projects
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应列表
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   items: Array<{
       *     createdAt: string
       *     defaultBranch: string | null
       *     deletedAt: string | null
       *     description: string | null
       *     hidePath: boolean
       *     id: string
       *     lastSyncAt: string | null
       *     name: string
       *     path: string
       *     remoteUrl: string | null
       *     updatedAt: string
       *     worktreeBasePath: string | null
       *   }> | null
       * }
       * ```
       */
      list<Config extends Alova2MethodConfig<ItemsResponseProjectBody>>(
        config?: Config
      ): Alova2Method<ItemsResponseProjectBody, 'project.list', Config>;
      /**
       * ---
       *
       * [POST] 创建项目
       *
       * **path:** /api/v1/projects/create
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 项目描述
       *   description: string
       *   // �Ƿ�����·��
       *   hidePath?: boolean
       *   // 项目名称
       *   name: string
       *   // 本地项目目录路径（可非 Git 仓库）
       *   path: string
       *   // Worktree 基础路径（可选，默认为项目目录下的 worktrees 子目录）
       *   worktreeBasePath?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     createdAt: string
       *     defaultBranch: string | null
       *     deletedAt: string | null
       *     description: string | null
       *     hidePath: boolean
       *     id: string
       *     lastSyncAt: string | null
       *     name: string
       *     path: string
       *     remoteUrl: string | null
       *     updatedAt: string
       *     worktreeBasePath: string | null
       *   }
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<ItemResponseProjectBody> & {
          data: CreateProjectInputBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseProjectBody, 'project.create', Config>;
      /**
       * ---
       *
       * [GET] 获取项目详情
       *
       * **path:** /api/v1/projects/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     createdAt: string
       *     defaultBranch: string | null
       *     deletedAt: string | null
       *     description: string | null
       *     hidePath: boolean
       *     id: string
       *     lastSyncAt: string | null
       *     name: string
       *     path: string
       *     remoteUrl: string | null
       *     updatedAt: string
       *     worktreeBasePath: string | null
       *   }
       * }
       * ```
       */
      getById<
        Config extends Alova2MethodConfig<ItemResponseProjectBody> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseProjectBody, 'project.getById', Config>;
      /**
       * ---
       *
       * [POST] 删除项目
       *
       * **path:** /api/v1/projects/{id}/delete
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'project.delete', Config>;
      /**
       * ---
       *
       * [POST] �༭��Ŀ
       *
       * **path:** /api/v1/projects/{id}/update
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // ��Ŀ����
       *   description: string
       *   // �Ƿ�����·��
       *   hidePath: boolean
       *   // ��Ŀ����
       *   name: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     createdAt: string
       *     defaultBranch: string | null
       *     deletedAt: string | null
       *     description: string | null
       *     hidePath: boolean
       *     id: string
       *     lastSyncAt: string | null
       *     name: string
       *     path: string
       *     remoteUrl: string | null
       *     updatedAt: string
       *     worktreeBasePath: string | null
       *   }
       * }
       * ```
       */
      update<
        Config extends Alova2MethodConfig<ItemResponseProjectBody> & {
          pathParams: {
            id: string;
          };
          data: UpdateProjectInputBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseProjectBody, 'project.update', Config>;
    };
    branch: {
      /**
       * ---
       *
       * [GET] 获取分支列表
       *
       * **path:** /api/v1/projects/{projectId}/branches
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     local: Array<{
       *       hasWorktree: boolean
       *       headCommit: string
       *       isCurrent: boolean
       *       isRemote: boolean
       *       name: string
       *     }> | null
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     remote: Array<{
       *       hasWorktree: boolean
       *       headCommit: string
       *       isCurrent: boolean
       *       isRemote: boolean
       *       name: string
       *     }> | null
       *   }
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<ItemResponseBranchListResultBody> & {
          pathParams: {
            projectId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseBranchListResultBody, 'branch.list', Config>;
      /**
       * ---
       *
       * [POST] 创建分支
       *
       * **path:** /api/v1/projects/{projectId}/branches/create
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 基础分支
       *   base: string
       *   // 同时创建 Worktree
       *   createWorktree: boolean
       *   // 分支名称
       *   name: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            projectId: string;
          };
          data: CreateBranchBody;
        }
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'branch.create', Config>;
      /**
       * ---
       *
       * [POST] 删除分支
       *
       * **path:** /api/v1/projects/{projectId}/branches/{branchName}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       *   branchName: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 强制删除
       *   force?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            projectId: string;
            branchName: string;
          };
          params: {
            /**
             * 强制删除
             */
            force?: boolean;
          };
        }
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'branch.delete', Config>;
      /**
       * ---
       *
       * [POST] 合并分支
       *
       * **path:** /api/v1/worktrees/{id}/merge
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // Squash 合并后立即提交
       *   commit: boolean
       *   // 提交信息（仅 squash 合并生效）
       *   commitMessage: string
       *   // 源分支
       *   sourceBranch: string
       *   // 合并策略
       *   strategy: 'merge' | 'rebase' | 'squash'
       *   // 目标分支
       *   targetBranch: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     conflicts: string[] | null
       *     message: string
       *     success: boolean
       *   }
       * }
       * ```
       */
      merge<
        Config extends Alova2MethodConfig<ItemResponseMergeResultBody> & {
          pathParams: {
            id: string;
          };
          data: MergeBranchBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseMergeResultBody, 'branch.merge', Config>;
    };
    worktree: {
      /**
       * ---
       *
       * [POST] 刷新所有 Worktree 状态
       *
       * **path:** /api/v1/projects/{projectId}/refresh-all-worktrees
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     // 刷新失败数量
       *     failed: number
       *     // 刷新成功数量
       *     updated: number
       *   }
       * }
       * ```
       */
      refreshAllByProject<
        Config extends Alova2MethodConfig<ItemResponseRefreshAllResultBody> & {
          pathParams: {
            projectId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseRefreshAllResultBody, 'worktree.refreshAllByProject', Config>;
      /**
       * ---
       *
       * [POST] 同步 Worktree
       *
       * **path:** /api/v1/projects/{projectId}/sync-worktrees
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      syncByProject<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            projectId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'worktree.syncByProject', Config>;
      /**
       * ---
       *
       * [GET] 获取 Worktree 列表
       *
       * **path:** /api/v1/projects/{projectId}/worktrees
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应列表
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   items: Array<{
       *     branchName: string
       *     createdAt: string
       *     deletedAt: string | null
       *     headCommit: string | null
       *     headCommitDate: string | null
       *     id: string
       *     isBare: boolean
       *     isMain: boolean
       *     path: string
       *     projectId: string
       *     statusAhead: number | null
       *     statusBehind: number | null
       *     statusConflicts: number | null
       *     statusModified: number | null
       *     statusStaged: number | null
       *     statusUntracked: number | null
       *     statusUpdatedAt: string | null
       *     updatedAt: string
       *   }> | null
       * }
       * ```
       */
      listByProject<
        Config extends Alova2MethodConfig<ItemsResponseWorktreeBody> & {
          pathParams: {
            projectId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ItemsResponseWorktreeBody, 'worktree.listByProject', Config>;
      /**
       * ---
       *
       * [POST] 创建 Worktree
       *
       * **path:** /api/v1/projects/{projectId}/worktrees/create
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 基础分支
       *   baseBranch: string
       *   // 分支名称
       *   branchName: string
       *   // 是否创建新分支
       *   createBranch: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     branchName: string
       *     createdAt: string
       *     deletedAt: string | null
       *     headCommit: string | null
       *     headCommitDate: string | null
       *     id: string
       *     isBare: boolean
       *     isMain: boolean
       *     path: string
       *     projectId: string
       *     statusAhead: number | null
       *     statusBehind: number | null
       *     statusConflicts: number | null
       *     statusModified: number | null
       *     statusStaged: number | null
       *     statusUntracked: number | null
       *     statusUpdatedAt: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<ItemResponseWorktreeBody> & {
          pathParams: {
            projectId: string;
          };
          data: Worktree_create_request;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseWorktreeBody, 'worktree.create', Config>;
      /**
       * ---
       *
       * [POST] 删除 Worktree
       *
       * **path:** /api/v1/worktrees/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   force?: boolean
       *   deleteBranch?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            id: string;
          };
          params: {
            force?: boolean;
            deleteBranch?: boolean;
          };
        }
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'worktree.delete', Config>;
      /**
       * ---
       *
       * [POST] 提交 Worktree 更改
       *
       * **path:** /api/v1/worktrees/{id}/commit
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提交信息
       *   message: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     branchName: string
       *     createdAt: string
       *     deletedAt: string | null
       *     headCommit: string | null
       *     headCommitDate: string | null
       *     id: string
       *     isBare: boolean
       *     isMain: boolean
       *     path: string
       *     projectId: string
       *     statusAhead: number | null
       *     statusBehind: number | null
       *     statusConflicts: number | null
       *     statusModified: number | null
       *     statusStaged: number | null
       *     statusUntracked: number | null
       *     statusUpdatedAt: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      commit<
        Config extends Alova2MethodConfig<ItemResponseWorktreeBody> & {
          pathParams: {
            id: string;
          };
          data: Worktree_commit_request;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseWorktreeBody, 'worktree.commit', Config>;
      /**
       * ---
       *
       * [POST] 刷新 Worktree 状态
       *
       * **path:** /api/v1/worktrees/{id}/refresh-status
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     branchName: string
       *     createdAt: string
       *     deletedAt: string | null
       *     headCommit: string | null
       *     headCommitDate: string | null
       *     id: string
       *     isBare: boolean
       *     isMain: boolean
       *     path: string
       *     projectId: string
       *     statusAhead: number | null
       *     statusBehind: number | null
       *     statusConflicts: number | null
       *     statusModified: number | null
       *     statusStaged: number | null
       *     statusUntracked: number | null
       *     statusUpdatedAt: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      refreshStatus<
        Config extends Alova2MethodConfig<ItemResponseWorktreeBody> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseWorktreeBody, 'worktree.refreshStatus', Config>;
    };
    task: {
      /**
       * ---
       *
       * [GET] 任务列表
       *
       * **path:** /api/v1/projects/{projectId}/tasks
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   status?: string
       *   worktreeId?: string
       *   priority?: string
       *   keyword?: string
       *   page?: number
       *   pageSize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 本次返回数量
       *   itemCount: number
       *   // 响应列表
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   items: Array<{
       *     completedAt: string | null
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     description: string
       *     dueDate: string | null
       *     id: string
       *     orderIndex: number
       *     priority: number
       *     project?: {
       *       createdAt: string
       *       defaultBranch: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       description: string
       *       hidePath: boolean
       *       id: string
       *       lastSyncAt: string | null
       *       name: string
       *       path: string
       *       remoteUrl: string
       *       updatedAt: string
       *       worktreeBasePath: string
       *     }
       *     projectId: string
       *     status: string
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     tags: string[] | null
       *     title: string
       *     updatedAt: string
       *     worktree?: {
       *       branchName: string
       *       createdAt: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       headCommit: string
       *       headCommitDate: string | null
       *       id: string
       *       isBare: boolean
       *       isMain: boolean
       *       path: string
       *       project?: {
       *         createdAt: string
       *         defaultBranch: string
       *         deletedAt: {
       *           Time: string
       *           Valid: boolean
       *         }
       *         description: string
       *         hidePath: boolean
       *         id: string
       *         lastSyncAt: string | null
       *         name: string
       *         path: string
       *         remoteUrl: string
       *         updatedAt: string
       *         worktreeBasePath: string
       *       }
       *       projectId: string
       *       statusAhead: number
       *       statusBehind: number
       *       statusConflicts: number
       *       statusModified: number
       *       statusStaged: number
       *       statusUntracked: number
       *       statusUpdatedAt: string | null
       *       updatedAt: string
       *     }
       *     worktreeId: string | null
       *   }> | null
       *   // 当前页码
       *   page: number
       *   // 每页数量
       *   pageSize: number
       *   // 记录总数
       *   total: number
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<PaginatedResponseTaskTableBody> & {
          pathParams: {
            projectId: string;
          };
          params: {
            status?: string;
            worktreeId?: string;
            priority?: string;
            keyword?: string;
            page?: number;
            pageSize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<PaginatedResponseTaskTableBody, 'task.list', Config>;
      /**
       * ---
       *
       * [POST] 创建任务
       *
       * **path:** /api/v1/projects/{projectId}/tasks/create
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 任务描述
       *   description: string
       *   // 截止日期
       *   dueDate: string | null
       *   // 优先级
       *   priority: number
       *   // 任务状态
       *   status: 'todo' | 'in_progress' | 'done' | 'archived'
       *   // 标签
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   tags: string[] | null
       *   // 任务标题
       *   title: string
       *   // 关联的 Worktree
       *   worktreeId: string | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     completedAt: string | null
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     description: string
       *     dueDate: string | null
       *     id: string
       *     orderIndex: number
       *     priority: number
       *     project?: {
       *       createdAt: string
       *       defaultBranch: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       description: string
       *       hidePath: boolean
       *       id: string
       *       lastSyncAt: string | null
       *       name: string
       *       path: string
       *       remoteUrl: string
       *       updatedAt: string
       *       worktreeBasePath: string
       *     }
       *     projectId: string
       *     status: string
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     tags: string[] | null
       *     title: string
       *     updatedAt: string
       *     worktree?: {
       *       branchName: string
       *       createdAt: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       headCommit: string
       *       headCommitDate: string | null
       *       id: string
       *       isBare: boolean
       *       isMain: boolean
       *       path: string
       *       project?: {
       *         createdAt: string
       *         defaultBranch: string
       *         deletedAt: {
       *           Time: string
       *           Valid: boolean
       *         }
       *         description: string
       *         hidePath: boolean
       *         id: string
       *         lastSyncAt: string | null
       *         name: string
       *         path: string
       *         remoteUrl: string
       *         updatedAt: string
       *         worktreeBasePath: string
       *       }
       *       projectId: string
       *       statusAhead: number
       *       statusBehind: number
       *       statusConflicts: number
       *       statusModified: number
       *       statusStaged: number
       *       statusUntracked: number
       *       statusUpdatedAt: string | null
       *       updatedAt: string
       *     }
       *     worktreeId: string | null
       *   }
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<ItemResponseTaskTableBody> & {
          pathParams: {
            projectId: string;
          };
          data: CreateTaskBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseTaskTableBody, 'task.create', Config>;
      /**
       * ---
       *
       * [GET] 任务详情
       *
       * **path:** /api/v1/tasks/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     completedAt: string | null
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     description: string
       *     dueDate: string | null
       *     id: string
       *     orderIndex: number
       *     priority: number
       *     project?: {
       *       createdAt: string
       *       defaultBranch: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       description: string
       *       hidePath: boolean
       *       id: string
       *       lastSyncAt: string | null
       *       name: string
       *       path: string
       *       remoteUrl: string
       *       updatedAt: string
       *       worktreeBasePath: string
       *     }
       *     projectId: string
       *     status: string
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     tags: string[] | null
       *     title: string
       *     updatedAt: string
       *     worktree?: {
       *       branchName: string
       *       createdAt: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       headCommit: string
       *       headCommitDate: string | null
       *       id: string
       *       isBare: boolean
       *       isMain: boolean
       *       path: string
       *       project?: {
       *         createdAt: string
       *         defaultBranch: string
       *         deletedAt: {
       *           Time: string
       *           Valid: boolean
       *         }
       *         description: string
       *         hidePath: boolean
       *         id: string
       *         lastSyncAt: string | null
       *         name: string
       *         path: string
       *         remoteUrl: string
       *         updatedAt: string
       *         worktreeBasePath: string
       *       }
       *       projectId: string
       *       statusAhead: number
       *       statusBehind: number
       *       statusConflicts: number
       *       statusModified: number
       *       statusStaged: number
       *       statusUntracked: number
       *       statusUpdatedAt: string | null
       *       updatedAt: string
       *     }
       *     worktreeId: string | null
       *   }
       * }
       * ```
       */
      getById<
        Config extends Alova2MethodConfig<ItemResponseTaskTableBody> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseTaskTableBody, 'task.getById', Config>;
      /**
       * ---
       *
       * [POST] 绑定/解绑 Worktree
       *
       * **path:** /api/v1/tasks/{id}/bind-worktree
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // Worktree ID（null 表示解绑）
       *   worktreeId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     completedAt: string | null
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     description: string
       *     dueDate: string | null
       *     id: string
       *     orderIndex: number
       *     priority: number
       *     project?: {
       *       createdAt: string
       *       defaultBranch: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       description: string
       *       hidePath: boolean
       *       id: string
       *       lastSyncAt: string | null
       *       name: string
       *       path: string
       *       remoteUrl: string
       *       updatedAt: string
       *       worktreeBasePath: string
       *     }
       *     projectId: string
       *     status: string
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     tags: string[] | null
       *     title: string
       *     updatedAt: string
       *     worktree?: {
       *       branchName: string
       *       createdAt: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       headCommit: string
       *       headCommitDate: string | null
       *       id: string
       *       isBare: boolean
       *       isMain: boolean
       *       path: string
       *       project?: {
       *         createdAt: string
       *         defaultBranch: string
       *         deletedAt: {
       *           Time: string
       *           Valid: boolean
       *         }
       *         description: string
       *         hidePath: boolean
       *         id: string
       *         lastSyncAt: string | null
       *         name: string
       *         path: string
       *         remoteUrl: string
       *         updatedAt: string
       *         worktreeBasePath: string
       *       }
       *       projectId: string
       *       statusAhead: number
       *       statusBehind: number
       *       statusConflicts: number
       *       statusModified: number
       *       statusStaged: number
       *       statusUntracked: number
       *       statusUpdatedAt: string | null
       *       updatedAt: string
       *     }
       *     worktreeId: string | null
       *   }
       * }
       * ```
       */
      bindWorktree<
        Config extends Alova2MethodConfig<ItemResponseTaskTableBody> & {
          pathParams: {
            id: string;
          };
          data: BindWorktreeBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseTaskTableBody, 'task.bindWorktree', Config>;
      /**
       * ---
       *
       * [POST] 删除任务
       *
       * **path:** /api/v1/tasks/{id}/delete
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'task.delete', Config>;
      /**
       * ---
       *
       * [POST] 移动任务
       *
       * **path:** /api/v1/tasks/{id}/move
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 排序索引
       *   orderIndex?: number
       *   // 新状态
       *   status?: string
       *   // 关联 Worktree
       *   worktreeId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     completedAt: string | null
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     description: string
       *     dueDate: string | null
       *     id: string
       *     orderIndex: number
       *     priority: number
       *     project?: {
       *       createdAt: string
       *       defaultBranch: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       description: string
       *       hidePath: boolean
       *       id: string
       *       lastSyncAt: string | null
       *       name: string
       *       path: string
       *       remoteUrl: string
       *       updatedAt: string
       *       worktreeBasePath: string
       *     }
       *     projectId: string
       *     status: string
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     tags: string[] | null
       *     title: string
       *     updatedAt: string
       *     worktree?: {
       *       branchName: string
       *       createdAt: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       headCommit: string
       *       headCommitDate: string | null
       *       id: string
       *       isBare: boolean
       *       isMain: boolean
       *       path: string
       *       project?: {
       *         createdAt: string
       *         defaultBranch: string
       *         deletedAt: {
       *           Time: string
       *           Valid: boolean
       *         }
       *         description: string
       *         hidePath: boolean
       *         id: string
       *         lastSyncAt: string | null
       *         name: string
       *         path: string
       *         remoteUrl: string
       *         updatedAt: string
       *         worktreeBasePath: string
       *       }
       *       projectId: string
       *       statusAhead: number
       *       statusBehind: number
       *       statusConflicts: number
       *       statusModified: number
       *       statusStaged: number
       *       statusUntracked: number
       *       statusUpdatedAt: string | null
       *       updatedAt: string
       *     }
       *     worktreeId: string | null
       *   }
       * }
       * ```
       */
      move<
        Config extends Alova2MethodConfig<ItemResponseTaskTableBody> & {
          pathParams: {
            id: string;
          };
          data: MoveTaskBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseTaskTableBody, 'task.move', Config>;
      /**
       * ---
       *
       * [POST] 更新任务
       *
       * **path:** /api/v1/tasks/{id}/update
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 任务描述
       *   description?: string
       *   // 截止日期
       *   dueDate?: string
       *   // 优先级
       *   priority?: number
       *   // 标签
       *   // [items] start
       *   // [items] end
       *   tags?: string[]
       *   // 任务标题
       *   title?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     completedAt: string | null
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     description: string
       *     dueDate: string | null
       *     id: string
       *     orderIndex: number
       *     priority: number
       *     project?: {
       *       createdAt: string
       *       defaultBranch: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       description: string
       *       hidePath: boolean
       *       id: string
       *       lastSyncAt: string | null
       *       name: string
       *       path: string
       *       remoteUrl: string
       *       updatedAt: string
       *       worktreeBasePath: string
       *     }
       *     projectId: string
       *     status: string
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     tags: string[] | null
       *     title: string
       *     updatedAt: string
       *     worktree?: {
       *       branchName: string
       *       createdAt: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       headCommit: string
       *       headCommitDate: string | null
       *       id: string
       *       isBare: boolean
       *       isMain: boolean
       *       path: string
       *       project?: {
       *         createdAt: string
       *         defaultBranch: string
       *         deletedAt: {
       *           Time: string
       *           Valid: boolean
       *         }
       *         description: string
       *         hidePath: boolean
       *         id: string
       *         lastSyncAt: string | null
       *         name: string
       *         path: string
       *         remoteUrl: string
       *         updatedAt: string
       *         worktreeBasePath: string
       *       }
       *       projectId: string
       *       statusAhead: number
       *       statusBehind: number
       *       statusConflicts: number
       *       statusModified: number
       *       statusStaged: number
       *       statusUntracked: number
       *       statusUpdatedAt: string | null
       *       updatedAt: string
       *     }
       *     worktreeId: string | null
       *   }
       * }
       * ```
       */
      update<
        Config extends Alova2MethodConfig<ItemResponseTaskTableBody> & {
          pathParams: {
            id: string;
          };
          data: UpdateTaskBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseTaskTableBody, 'task.update', Config>;
    };
    terminalSession: {
      /**
       * ---
       *
       * [GET] 获取终端会话列表
       *
       * **path:** /api/v1/projects/{projectId}/terminals
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应列表
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   items: Array<{
       *     cols: number
       *     createdAt: string
       *     encoding: string
       *     id: string
       *     lastActive: string
       *     projectId: string
       *     rows: number
       *     status: string
       *     title: string
       *     workingDir: string
       *     worktreeId: string
       *     wsPath: string
       *     wsUrl: string
       *   }> | null
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<ItemsResponseTerminalSessionViewBody> & {
          pathParams: {
            projectId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ItemsResponseTerminalSessionViewBody, 'terminalSession.list', Config>;
      /**
       * ---
       *
       * [POST] 关闭终端会话
       *
       * **path:** /api/v1/projects/{projectId}/terminals/{sessionId}/close
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       *   sessionId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      close<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            projectId: string;
            sessionId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'terminalSession.close', Config>;
      /**
       * ---
       *
       * [POST] 终端标签重命名
       *
       * **path:** /api/v1/projects/{projectId}/terminals/{sessionId}/rename
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       *   sessionId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 新的终端标签名
       *   title: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     cols: number
       *     createdAt: string
       *     encoding: string
       *     id: string
       *     lastActive: string
       *     projectId: string
       *     rows: number
       *     status: string
       *     title: string
       *     workingDir: string
       *     worktreeId: string
       *     wsPath: string
       *     wsUrl: string
       *   }
       * }
       * ```
       */
      rename<
        Config extends Alova2MethodConfig<ItemResponseTerminalSessionViewBody> & {
          pathParams: {
            projectId: string;
            sessionId: string;
          };
          data: TerminalRenameInputBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseTerminalSessionViewBody, 'terminalSession.rename', Config>;
      /**
       * ---
       *
       * [POST] 创建终端会话
       *
       * **path:** /api/v1/projects/{projectId}/worktrees/{worktreeId}/terminals
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       *   worktreeId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 终端列数
       *   cols: number
       *   // 终端行数
       *   rows: number
       *   // 终端标题
       *   title: string
       *   // 工作目录
       *   workingDir: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     cols: number
       *     createdAt: string
       *     encoding: string
       *     id: string
       *     lastActive: string
       *     projectId: string
       *     rows: number
       *     status: string
       *     title: string
       *     workingDir: string
       *     worktreeId: string
       *     wsPath: string
       *     wsUrl: string
       *   }
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<ItemResponseTerminalSessionViewBody> & {
          pathParams: {
            projectId: string;
            worktreeId: string;
          };
          data: TerminalCreateInputBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseTerminalSessionViewBody, 'terminalSession.create', Config>;
    };
    ptyTest: {
      /**
       * ---
       *
       * [POST] 创建 PTY 测试会话
       *
       * **path:** /api/v1/pty-test/sessions
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 终端列数
       *   cols: number
       *   // xpty 输出编码，默认 utf-8
       *   encoding: string
       *   // 终端行数
       *   rows: number
       *   // 自定义 shell 命令，留空使用默认配置
       *   shell: string
       *   // 工作目录，可选
       *   workingDir: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     cols: number
       *     createdAt: string
       *     encoding: string
       *     id: string
       *     rows: number
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     shell: string[] | null
       *     workingDir: string
       *     wsPath: string
       *     wsUrl: string
       *   }
       * }
       * ```
       */
      sessionCreate<
        Config extends Alova2MethodConfig<ItemResponsePtyTestSessionViewBody> & {
          data: PtyTestCreateInputBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponsePtyTestSessionViewBody, 'ptyTest.sessionCreate', Config>;
      /**
       * ---
       *
       * [POST] 关闭 PTY 测试会话
       *
       * **path:** /api/v1/pty-test/sessions/{sessionId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   sessionId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      sessionClose<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            sessionId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'ptyTest.sessionClose', Config>;
    };
    system: {
      /**
       * ---
       *
       * [POST] 打开文件管理器
       *
       * **path:** /api/v1/system/open-explorer
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 目标路径
       *   path: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      openExplorer<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          data: OpenPathInputBody;
        }
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'system.openExplorer', Config>;
      /**
       * ---
       *
       * [POST] 打开终端
       *
       * **path:** /api/v1/system/open-terminal
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 目标路径
       *   path: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      openTerminal<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          data: OpenPathInputBody;
        }
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'system.openTerminal', Config>;
    };
    taskComment: {
      /**
       * ---
       *
       * [POST] 删除评论
       *
       * **path:** /api/v1/task-comments/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'taskComment.delete', Config>;
      /**
       * ---
       *
       * [GET] 评论列表
       *
       * **path:** /api/v1/tasks/{id}/comments
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应列表
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   items: Array<{
       *     content: string
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     id: string
       *     task?: {
       *       completedAt: string | null
       *       createdAt: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       description: string
       *       dueDate: string | null
       *       id: string
       *       orderIndex: number
       *       priority: number
       *       project?: {
       *         createdAt: string
       *         defaultBranch: string
       *         deletedAt: {
       *           Time: string
       *           Valid: boolean
       *         }
       *         description: string
       *         hidePath: boolean
       *         id: string
       *         lastSyncAt: string | null
       *         name: string
       *         path: string
       *         remoteUrl: string
       *         updatedAt: string
       *         worktreeBasePath: string
       *       }
       *       projectId: string
       *       status: string
       *       // [params1] start
       *       // [items] start
       *       // [items] end
       *       // [params1] end
       *       tags: string[] | null
       *       title: string
       *       updatedAt: string
       *       worktree?: {
       *         branchName: string
       *         createdAt: string
       *         deletedAt: {
       *           Time: string
       *           Valid: boolean
       *         }
       *         headCommit: string
       *         headCommitDate: string | null
       *         id: string
       *         isBare: boolean
       *         isMain: boolean
       *         path: string
       *         project?: {
       *           createdAt: string
       *           defaultBranch: string
       *           deletedAt: {
       *             Time: string
       *             Valid: boolean
       *           }
       *           description: string
       *           hidePath: boolean
       *           id: string
       *           lastSyncAt: string | null
       *           name: string
       *           path: string
       *           remoteUrl: string
       *           updatedAt: string
       *           worktreeBasePath: string
       *         }
       *         projectId: string
       *         statusAhead: number
       *         statusBehind: number
       *         statusConflicts: number
       *         statusModified: number
       *         statusStaged: number
       *         statusUntracked: number
       *         statusUpdatedAt: string | null
       *         updatedAt: string
       *       }
       *       worktreeId: string | null
       *     }
       *     taskId: string
       *     updatedAt: string
       *   }> | null
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<ItemsResponseTaskCommentTableBody> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ItemsResponseTaskCommentTableBody, 'taskComment.list', Config>;
      /**
       * ---
       *
       * [POST] 新增评论
       *
       * **path:** /api/v1/tasks/{id}/comments/create
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 评论内容
       *   content: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     content: string
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     id: string
       *     task?: {
       *       completedAt: string | null
       *       createdAt: string
       *       deletedAt: {
       *         Time: string
       *         Valid: boolean
       *       }
       *       description: string
       *       dueDate: string | null
       *       id: string
       *       orderIndex: number
       *       priority: number
       *       project?: {
       *         createdAt: string
       *         defaultBranch: string
       *         deletedAt: {
       *           Time: string
       *           Valid: boolean
       *         }
       *         description: string
       *         hidePath: boolean
       *         id: string
       *         lastSyncAt: string | null
       *         name: string
       *         path: string
       *         remoteUrl: string
       *         updatedAt: string
       *         worktreeBasePath: string
       *       }
       *       projectId: string
       *       status: string
       *       // [params1] start
       *       // [items] start
       *       // [items] end
       *       // [params1] end
       *       tags: string[] | null
       *       title: string
       *       updatedAt: string
       *       worktree?: {
       *         branchName: string
       *         createdAt: string
       *         deletedAt: {
       *           Time: string
       *           Valid: boolean
       *         }
       *         headCommit: string
       *         headCommitDate: string | null
       *         id: string
       *         isBare: boolean
       *         isMain: boolean
       *         path: string
       *         project?: {
       *           createdAt: string
       *           defaultBranch: string
       *           deletedAt: {
       *             Time: string
       *             Valid: boolean
       *           }
       *           description: string
       *           hidePath: boolean
       *           id: string
       *           lastSyncAt: string | null
       *           name: string
       *           path: string
       *           remoteUrl: string
       *           updatedAt: string
       *           worktreeBasePath: string
       *         }
       *         projectId: string
       *         statusAhead: number
       *         statusBehind: number
       *         statusConflicts: number
       *         statusModified: number
       *         statusStaged: number
       *         statusUntracked: number
       *         statusUpdatedAt: string | null
       *         updatedAt: string
       *       }
       *       worktreeId: string | null
       *     }
       *     taskId: string
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<ItemResponseTaskCommentTableBody> & {
          pathParams: {
            id: string;
          };
          data: CreateCommentBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseTaskCommentTableBody, 'taskComment.create', Config>;
    };
    upload: {
      /**
       * ---
       *
       * [POST] 上传剪贴板图片
       *
       * **path:** /api/v1/upload/clipboard-image
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 图片数据（base64 编码）
       *   data: string
       *   // 文件名
       *   fileName: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     // 文件名
       *     fileName: string
       *     // 文件路径
       *     path: string
       *     // 文件大小（字节）
       *     size: number
       *   }
       * }
       * ```
       */
      clipboardImage<
        Config extends Alova2MethodConfig<ItemResponseUploadImageResponseBody> & {
          data: UploadClipboardImageInputBody;
        }
      >(
        config: Config
      ): Alova2Method<ItemResponseUploadImageResponseBody, 'upload.clipboardImage', Config>;
    };
  }

  var Apis: Apis;
}
